为本科毕业设计论文添加了封面
Aetf/xjtuthesis pull request #36
Opened 2021-05-04 14:20 UTC by qsdrqs

根据教务处2021年本科毕业设计最新模板(http://pts.xjtu.edu.cn:8080/shownews.aspx?newsno=ICWsMBFPa0Sq99BvC2PpEg....)(需要挂学校vpn访问)，本科毕业设计加入了如下图所示的封面：
![图片](https://user-images.githubusercontent.com/55623213/117017287-10f84280-ad26-11eb-869b-b4ca915dd543.png)
我在原有硕士，博士的封面基础上，为本科毕业设计制作了封面：
![图片](https://user-images.githubusercontent.com/55623213/117017608-4ef56680-ad26-11eb-8154-dd3151fd6fd4.png)
同时根据教务处对内容规定的模板(http://pts.xjtu.edu.cn:8080/shownews.aspx?newsno=JfHjh3GoxHX6SaqGDYbeAg....)，删除了原有在摘要中出现的项目介绍。

与教务处模板不同的是，这个封面保留了所有字体都是黑色的特性。

目前存在的问题有：当毕业设计标题过长时，标题内容会溢出下划线的盒子

2021-05-04 19:54 UTC, Aetf commented
感谢 PR！可惜我现在已经没有学校 VPN 了。 几个小问题：

* 封面字体颜色可以与教务处模板不一致吗？这个现在学校是怎么要求的？
* 封面底部的日期字体与模板不一致

2021-05-04 21:12 UTC, Aetf requested changes
除了 `ulem` 的问题外，
`\makebox` 不是很灵活，考虑一下`\hfill` 加上 `hanging` 包的`\hangpara`来实现？

https://www.overleaf.com/read/ddyvbgtzzzfz

2021-05-05 09:30 UTC, qsdrqs commented
感谢指导！我已经按提示用 `CJKunderline` 代替 `makebox` 来添加下划线，在我这里效果也很好了。同时调整了封面底部日期的字体。

目前还不太清楚教务处是否对颜色有要求，出于兼容的目的，还是把整个标题页全部改成红色了。红色校徽使用的是教务处模板中的图片，清晰度不如本项目中的黑色校徽，但整体看上去问题不大：
![图片](https://user-images.githubusercontent.com/55623213/117121681-82d49880-adc7-11eb-9b4b-a07000f2aabb.png)

2021-05-05 14:43 UTC, Aetf commented
Cool!

2021-05-05 14:43 UTC, merged