根据 2024 届毕设 Word 模板的一些更新
Aetf/xjtuthesis pull request #52
Opened 2024-06-04 13:07 UTC by ShunchiZhang

注：`>` 中内容均引自《2024届本科毕业设计（论文）模版》

## [`b5b8832`](https://github.com/ShunchiZhang/xjtuthesis/commit/b5b8832) 修正了摘要和致谢中间的空格

> - **摘要**：……居中编排“摘  要”二字（三号宋体），**字间空两个半角字符**……
> - **致谢**：……居中编排“致  谢”二字（三号宋体），**字间空两个半角字符**……

## [`d8e288c`](https://github.com/ShunchiZhang/xjtuthesis/commit/d8e288c) 修正了图序与表序的前后空格

> - 图序前空1字符，图序后空2字符
> - 表序前不空格，表序后空1字

这里没说是全角字符还是半角字符，但模板中实际使用的是半角。

## [`ea221fa`](https://github.com/ShunchiZhang/xjtuthesis/commit/ea221fa) 修正了附录奇数页页眉

> 附录包括：A外文原文、B外文翻译、C有关图纸、D计算机源程序……，此部分内容页眉同上文（**奇数页为一级标题内容**，偶数页为“西安交通大学本科毕业设计（论文）”）

为了不影响硕博格式，仅在 `\ifxjtu@bachelor` 中调整

## [`c12b835`](https://github.com/ShunchiZhang/xjtuthesis/commit/c12b835) 增加了文末插入 PDF 的功能（任务书等）

> 附录后依次编排
> - 《任务书》（双面打印，**奇数页起排**）
> - 《考核评议书》（双面打印，**奇数页起排**，背面是《评审意见书》）
> - 《答辩结果》（**奇数页起排**）
> 此部分内容**不再额外添加“附录X”一级标题**，页眉和排版严格参照模板文件。
> 
> 以上全部内容须与论文装订在一起，**且页码必须接着参考文献的页码连续编写**。

2024-06-04 13:50 UTC, ShunchiZhang commented
还有一些非强制但也许有用的更新（其实应该开 branch 提另一个 PR 来着）

## [`5d9385e`](https://github.com/ShunchiZhang/xjtuthesis/commit/5d9385e) 使用了楷体作为斜体

使用 SimKai (Windows) 或 Kaiti SC (Mac) 作为 `\textit` 默认斜体，同时用户仍可通过 `\textsf` 实现基于宋体的伪斜体。

## [`8348605`](https://github.com/ShunchiZhang/xjtuthesis/commit/8348605) 提供了 `tarbularx` 表格的对齐设置

根据《2024届本科毕业设计（论文）模版》：
> 表格必须通栏，即**表格宽度与正文版面平齐**

也就是说必须使用 `tabularx` 实现表格。于是提供了基于 `tabularx` 的左、中、右对齐设置。示例如下：

```latex
\begin{tabularx}{\textwidth}{LCR}
% table here %
\end{tabularx}
```

## [`3795051`](https://github.com/ShunchiZhang/xjtuthesis/commit/3795051) 修正了多行图题与表题的行距设置

注意到多行图题或表题的情况下，默认行距过小，导致观感十分拥挤，所以使用与其它格式均一致的 1.2 倍行距。

而且前文多了一行 `\captionsetup`，会被后文的覆盖，所以把前文的删除了。

## [`2341b9c`](https://github.com/ShunchiZhang/xjtuthesis/commit/2341b9c) 提供了 `proof` 环境以编写证明

以无缩进加粗"证明" + 全角冒号开头，以右对齐 QED 标志结尾。

2024-06-07 05:12 UTC, Zipper-1 commented
我们明确指出了不能宋体之外的字体，不能有加粗和斜体

2024-06-07 09:32 UTC, ShunchiZhang commented
> 我们在答辩时明确指出了不能宋体之外的字体，不能有加粗和斜体

@Zipper-1 谢谢指出。模板上确实没明确说粗体斜体能不能用，应该是不同学院还有细化要求，那我 [5d9385e](https://github.com/ShunchiZhang/xjtuthesis/commit/5d9385e) 为了兼容性就撤了。

考虑到我第 2 波 commit 是非标准要求，我还是在 master 上只保留了第 1 波 commit，然后第 2 波开新 branch 提新 PR。

2024-06-07 09:46 UTC, ShunchiZhang commented
> 我们在答辩时明确指出了不能宋体之外的字体，不能有加粗和斜体

Sorry 我开完新 branch 和新 PR 才看到你在我的 repo 已经提 PR 改了，那我还是把新 branch 的 PR 关了。

2024-06-07 09:58 UTC, ShunchiZhang commented
Comments copied from ShunchiZhang/xjtuthesis#1 (Credit @Zipper-1)

- 删除了答辩明确禁止的楷体字体 ([`83186eb`](https://github.com/ShunchiZhang/xjtuthesis/pull/1/commits/83186eb))
- 引入 `importsheet` 命令来导入外部 pdf 并从奇数页起排 ([`589336a`](https://github.com/ShunchiZhang/xjtuthesis/pull/1/commits/589336a), [`6edb0b7`](https://github.com/ShunchiZhang/xjtuthesis/pull/1/commits/6edb0b7))
- 使用 `listings` 包来在附录中添加代码 ([`3097407`](https://github.com/ShunchiZhang/xjtuthesis/pull/1/commits/3097407))
- 按模板修改各级标题的缩进与前后行距 ([`0871a98`](https://github.com/ShunchiZhang/xjtuthesis/pull/1/commits/0871a98))

2024-06-07 10:26 UTC, Zipper-1 commented
多行图题与表题的行距其实可以算标准要求，word模板里面的行距也是1.2倍，我们专业也有同学答辩这个问题被说了

2024-06-08 06:50 UTC, Aetf requested changes
感谢～ 就只有一个小comment

2024-06-08 06:50 UTC, Aetf commented on base/xjtuthesis.cls
> +\RequirePackage{xcolor}
xcolor 在第100行写过了

2024-06-08 07:45 UTC, ShunchiZhang commented on base/xjtuthesis.cls
> +\RequirePackage{xcolor}
谢谢指出，已修改

2024-06-08 18:57 UTC, Aetf approved these changes

2024-06-08 18:58 UTC, merged